(cl:defpackage fast_cam-srv
  (:use )
  (:export
   "GETCAMERAPROPERTIES"
   "<GETCAMERAPROPERTIES-REQUEST>"
   "GETCAMERAPROPERTIES-REQUEST"
   "<GETCAMERAPROPERTIES-RESPONSE>"
   "GETCAMERAPROPERTIES-RESPONSE"
   "SETGAIN"
   "<SETGAIN-REQUEST>"
   "SETGAIN-REQUEST"
   "<SETGAIN-RESPONSE>"
   "SETGAIN-RESPONSE"
  ))

