// Generated by gencpp from file fast_cam/GetCameraProperties.msg
// DO NOT EDIT!


#ifndef FAST_CAM_MESSAGE_GETCAMERAPROPERTIES_H
#define FAST_CAM_MESSAGE_GETCAMERAPROPERTIES_H

#include <ros/service_traits.h>


#include <fast_cam/GetCameraPropertiesRequest.h>
#include <fast_cam/GetCameraPropertiesResponse.h>


namespace fast_cam
{

struct GetCameraProperties
{

typedef GetCameraPropertiesRequest Request;
typedef GetCameraPropertiesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetCameraProperties
} // namespace fast_cam


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fast_cam::GetCameraProperties > {
  static const char* value()
  {
    return "ca77d29133bf5a9bfbfacc01b41e087c";
  }

  static const char* value(const ::fast_cam::GetCameraProperties&) { return value(); }
};

template<>
struct DataType< ::fast_cam::GetCameraProperties > {
  static const char* value()
  {
    return "fast_cam/GetCameraProperties";
  }

  static const char* value(const ::fast_cam::GetCameraProperties&) { return value(); }
};


// service_traits::MD5Sum< ::fast_cam::GetCameraPropertiesRequest> should match
// service_traits::MD5Sum< ::fast_cam::GetCameraProperties >
template<>
struct MD5Sum< ::fast_cam::GetCameraPropertiesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fast_cam::GetCameraProperties >::value();
  }
  static const char* value(const ::fast_cam::GetCameraPropertiesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fast_cam::GetCameraPropertiesRequest> should match
// service_traits::DataType< ::fast_cam::GetCameraProperties >
template<>
struct DataType< ::fast_cam::GetCameraPropertiesRequest>
{
  static const char* value()
  {
    return DataType< ::fast_cam::GetCameraProperties >::value();
  }
  static const char* value(const ::fast_cam::GetCameraPropertiesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fast_cam::GetCameraPropertiesResponse> should match
// service_traits::MD5Sum< ::fast_cam::GetCameraProperties >
template<>
struct MD5Sum< ::fast_cam::GetCameraPropertiesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fast_cam::GetCameraProperties >::value();
  }
  static const char* value(const ::fast_cam::GetCameraPropertiesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fast_cam::GetCameraPropertiesResponse> should match
// service_traits::DataType< ::fast_cam::GetCameraProperties >
template<>
struct DataType< ::fast_cam::GetCameraPropertiesResponse>
{
  static const char* value()
  {
    return DataType< ::fast_cam::GetCameraProperties >::value();
  }
  static const char* value(const ::fast_cam::GetCameraPropertiesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FAST_CAM_MESSAGE_GETCAMERAPROPERTIES_H
