// Generated by gencpp from file fast_cam/GetCameraPropertiesRequest.msg
// DO NOT EDIT!


#ifndef FAST_CAM_MESSAGE_GETCAMERAPROPERTIESREQUEST_H
#define FAST_CAM_MESSAGE_GETCAMERAPROPERTIESREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fast_cam
{
template <class ContainerAllocator>
struct GetCameraPropertiesRequest_
{
  typedef GetCameraPropertiesRequest_<ContainerAllocator> Type;

  GetCameraPropertiesRequest_()
    {
    }
  GetCameraPropertiesRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::fast_cam::GetCameraPropertiesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fast_cam::GetCameraPropertiesRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetCameraPropertiesRequest_

typedef ::fast_cam::GetCameraPropertiesRequest_<std::allocator<void> > GetCameraPropertiesRequest;

typedef boost::shared_ptr< ::fast_cam::GetCameraPropertiesRequest > GetCameraPropertiesRequestPtr;
typedef boost::shared_ptr< ::fast_cam::GetCameraPropertiesRequest const> GetCameraPropertiesRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fast_cam::GetCameraPropertiesRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fast_cam::GetCameraPropertiesRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace fast_cam

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fast_cam::GetCameraPropertiesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fast_cam::GetCameraPropertiesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fast_cam::GetCameraPropertiesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fast_cam::GetCameraPropertiesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fast_cam::GetCameraPropertiesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fast_cam::GetCameraPropertiesRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fast_cam::GetCameraPropertiesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::fast_cam::GetCameraPropertiesRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::fast_cam::GetCameraPropertiesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fast_cam/GetCameraPropertiesRequest";
  }

  static const char* value(const ::fast_cam::GetCameraPropertiesRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fast_cam::GetCameraPropertiesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# string set_gain\n"
;
  }

  static const char* value(const ::fast_cam::GetCameraPropertiesRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fast_cam::GetCameraPropertiesRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetCameraPropertiesRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fast_cam::GetCameraPropertiesRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::fast_cam::GetCameraPropertiesRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // FAST_CAM_MESSAGE_GETCAMERAPROPERTIESREQUEST_H
