// Generated by gencpp from file fast_cam/SetGain.msg
// DO NOT EDIT!


#ifndef FAST_CAM_MESSAGE_SETGAIN_H
#define FAST_CAM_MESSAGE_SETGAIN_H

#include <ros/service_traits.h>


#include <fast_cam/SetGainRequest.h>
#include <fast_cam/SetGainResponse.h>


namespace fast_cam
{

struct SetGain
{

typedef SetGainRequest Request;
typedef SetGainResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetGain
} // namespace fast_cam


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::fast_cam::SetGain > {
  static const char* value()
  {
    return "a488df2b1501fa6d6dcdbca9c188eeff";
  }

  static const char* value(const ::fast_cam::SetGain&) { return value(); }
};

template<>
struct DataType< ::fast_cam::SetGain > {
  static const char* value()
  {
    return "fast_cam/SetGain";
  }

  static const char* value(const ::fast_cam::SetGain&) { return value(); }
};


// service_traits::MD5Sum< ::fast_cam::SetGainRequest> should match
// service_traits::MD5Sum< ::fast_cam::SetGain >
template<>
struct MD5Sum< ::fast_cam::SetGainRequest>
{
  static const char* value()
  {
    return MD5Sum< ::fast_cam::SetGain >::value();
  }
  static const char* value(const ::fast_cam::SetGainRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::fast_cam::SetGainRequest> should match
// service_traits::DataType< ::fast_cam::SetGain >
template<>
struct DataType< ::fast_cam::SetGainRequest>
{
  static const char* value()
  {
    return DataType< ::fast_cam::SetGain >::value();
  }
  static const char* value(const ::fast_cam::SetGainRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::fast_cam::SetGainResponse> should match
// service_traits::MD5Sum< ::fast_cam::SetGain >
template<>
struct MD5Sum< ::fast_cam::SetGainResponse>
{
  static const char* value()
  {
    return MD5Sum< ::fast_cam::SetGain >::value();
  }
  static const char* value(const ::fast_cam::SetGainResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::fast_cam::SetGainResponse> should match
// service_traits::DataType< ::fast_cam::SetGain >
template<>
struct DataType< ::fast_cam::SetGainResponse>
{
  static const char* value()
  {
    return DataType< ::fast_cam::SetGain >::value();
  }
  static const char* value(const ::fast_cam::SetGainResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FAST_CAM_MESSAGE_SETGAIN_H
