// Generated by gencpp from file fast_cam/SetGainResponse.msg
// DO NOT EDIT!


#ifndef FAST_CAM_MESSAGE_SETGAINRESPONSE_H
#define FAST_CAM_MESSAGE_SETGAINRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fast_cam
{
template <class ContainerAllocator>
struct SetGainResponse_
{
  typedef SetGainResponse_<ContainerAllocator> Type;

  SetGainResponse_()
    : success(false)
    , message()  {
    }
  SetGainResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::fast_cam::SetGainResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fast_cam::SetGainResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetGainResponse_

typedef ::fast_cam::SetGainResponse_<std::allocator<void> > SetGainResponse;

typedef boost::shared_ptr< ::fast_cam::SetGainResponse > SetGainResponsePtr;
typedef boost::shared_ptr< ::fast_cam::SetGainResponse const> SetGainResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fast_cam::SetGainResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fast_cam::SetGainResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fast_cam::SetGainResponse_<ContainerAllocator1> & lhs, const ::fast_cam::SetGainResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fast_cam::SetGainResponse_<ContainerAllocator1> & lhs, const ::fast_cam::SetGainResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fast_cam

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::fast_cam::SetGainResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fast_cam::SetGainResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fast_cam::SetGainResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fast_cam::SetGainResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fast_cam::SetGainResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fast_cam::SetGainResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fast_cam::SetGainResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::fast_cam::SetGainResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937c9679a518e3a1ULL;
  static const uint64_t static_value2 = 0x8d831e57125ea522ULL;
};

template<class ContainerAllocator>
struct DataType< ::fast_cam::SetGainResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fast_cam/SetGainResponse";
  }

  static const char* value(const ::fast_cam::SetGainResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fast_cam::SetGainResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Response part\n"
"bool success\n"
"string message\n"
;
  }

  static const char* value(const ::fast_cam::SetGainResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fast_cam::SetGainResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetGainResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fast_cam::SetGainResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fast_cam::SetGainResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FAST_CAM_MESSAGE_SETGAINRESPONSE_H
